---
title: "Local"
description: |
 
---


Chapecó é uma cidade jovem e acolhedora. Contando 100 anos a partir de sua fundação, ela atrai pessoas de diversas partes do país para enriquecer seus currículos nas instituições de ensino técnico e superior estabelecidas na cidade. Com aproximadamente 220 mil habitantes, a cidade oferece comércio e serviços que atendem toda a região Oeste de Santa Catarina.

Chapecó foi planejada em avenidas e tem infraestrutura aeroportuária, facilitando o trânsito de pessoas que tem interesse na cidade e nas pequenas e grandes empresas instaladas no município, além de rede hoteleira e diversificada gastronomia. O setor agropecuário da cidade destaca-se na suinocultura, avicultura, bovinocultura, produção leiteira e nos cultivos de soja, milho e erva-mate e na produção florestal. Esse setor é representado principalmente pela agricultura familiar.

Catedral de Santo Antônio e Desbravador
Foto: Emerson L. Silva

O EpidemioBrasil será realizado no Centro de Treinamento da Epagri, em Chapecó. É um local afastado do centro da cidade e muito agradável. O auditório principal é equipado com projetor, ar condicionado e cadeiras confortáveis. Tem um refeitório servido por uma cozinha industrial e salas de convivência, perfeitas para coffee breaks e exposição de posteres. Tem também salas para reuniões ou para trabalho individual. O participante pode, inclusive, se hospedar no Centro de Treinamento, com quartos coletivos, todos com ar-condicionado e wi-fi.