---
title: "Onde ficar"
description: |
---

**Aeroporto de Chapecó -- Serafim Enoss Bertaso (XAP)**

O aeroporto de Chapecó é atendido pelas empresas Azul, Gol e Latam, com chegadas e saídas para Campinas (SP), Guarulhos (SP) e Florianópolis (SC).

------------------------------------------------------------------------

**Hotéis**

Recomendamos abaixo hotéis que estão com tarifas diferenciadas para o EpidemioBrasil, de modo que seja facilitado o transporte solidário para o Centro de Treinamento da Epagri. Entretanto, a cidade dispõe de outras opções a serem consultadas pelo participante. Solicita-se que cada participante realize a própria reserva!


------------------------------------------------------------------------

**Partner by Almasty**

Diárias: 1 pessoa - R\$ 120,00; 2 pessoas - R\$ 180,00; 3 pessoas - R\$ 210,00; 4 pessoas - 280,00. Observações: ISS de 4% sobre as diárias. Apartamentos luxo com TV à cabo (Led 32'), frigobar, telefone, ducha, climatizador e Wi-fi, café da manhã incluso. Garagem: R\$ 15,00 a diária.

Site: <http://www.almasty.com.br> \
Contato: Whatsapp 47 99629 2483.

------------------------------------------------------------------------

**Lang Hotel**

**Diárias**: Single - R\$ 164,00; Double - R\$ 212,00; Triplo - R\$ 252,00. Observações: ISS de 4% sobre as diárias + R\$ 1,20 de taxa de turismo por quarto. Café da manhã incluso. Garagem: R\$ 15,00 a diária.

Site: <http://www.langhotel.com.br> \
Contato: [reservas\@langhotel.com.br](mailto:reservas@langhotel.com.br){.email}.

------------------------------------------------------------------------

**Mogano Business**

Diárias: Individual R$165,00 + 4% de ISS; Apartamento duplo - R$ 230,00 + 4% de ISS; Estacionamento R\$15,00 + 4% de ISS. Diárias incluem Café da manhã incluso.

Site: <http://www.moganohoteis.com.br> \
Contato: [comercial2\@moganobusiness.com.br](mailto:comercial2@moganobusiness.com.br){.email}.

------------------------------------------------------------------------

**Mogano Express**

Diárias: R\$150,00 + 4% de ISS para apartamento individual; R\$199,00 + 4% de ISS para apartamento duplo; R\$5,00 + 4% de ISS para garagem. Diárias com café da manhã e wifi incluídos.

Site: <http://www.moganohoteis.com.br> \
Contato: [gerencia\@moganoexpress.com.br](mailto:gerencia@moganoexpress.com.br){.email}

------------------------------------------------------------------------

**Ibis**

Individual: R\$169,00 + 4% de ISS, com café da manhã e estacionamento, por diária e por apartamento; Duplo (02 camas de solteiro ou 01 cama de casal): R\$209,00 + 4% de ISS, com café da manhã e estacionamento, por diária e por apartamento. Informar ao nosso atendente que a reserva é para: EPAGRI/EpidemioBrasil.

Contato: email: [h9362-re\@accor.com](mailto:h9362-re@accor.com){.email}\
WhatspApp (49) 3311-3000

------------------------------------------------------------------------

**Slaviero**

Apto Luxo SGL - R\$185,00+4%iss Apto Luxo DBL - R\$215,00+4%iss Apto Luxo Triplo - R\$245,00+4%iss *valor incluso café da manhã* estacionamento cortesia (mediante disponibilidade).

Contato: email: [comercial.sech\@slavierohoteis.com.br](mailto:comercial.sech@slavierohoteis.com.br){.email}; \
WhatspApp (49) 98894-8139

------------------------------------------------------------------------

**Eston**

Diárias: Standard Individual - R\$ 145,00; Standard Duplo - R\$ 199,00; Standard Triplo - R\$ 239,00; Luxo Individual - R\$ 157,00; Luxo Duplo - R\$ 217,00. Observações: ISS de 4% sobre as diárias. Café da manhã incluso. Garagem: R\$ 12,00 a diária.

Site: <http://www.estonhotel.com.br> \
Contato: [reservas\@estonhotel.com.br](mailto:reservas@estonhotel.com.br){.email}

------------------------------------------------------------------------

**North**

Tarifa normal: Individual - R\$ 169,90; Duplo - R\$ 249,90; Triplo - R\$ 360,00; Quadruplo - R\$ 450,00. Tarifas para fechamento de 5 apartamentos - Ativada no momento da 5ª reserva mencionando o evento: Individual - R\$ 159,90; Duplo - R\$ 229,90; Triplo - R\$ 319,90; Quadruplo - R\$ 399,00. Observações: cama box, ar condicionado Split, frigobar, televisor LED com canais fechados, Home Office e Wi-Fi livre. Café da manhã incluso. Garagem coberta com segurança 24 h. Transfer hotel/aeroporto: R\$ 80,00 para até 4 pessoas independente do horário.

Site: <http://www.hotelnorth.com.br> \
Contato: 49 8400 0737

------------------------------------------------------------------------

**Cetrec -** Centro de Treinamento da Epagri Chapecó

Tarifas: Pernoite sem café-da-manhã - R\$ 71,00; Café da manhã - R\$ 13,00; Jantar - R\$ 17,00. Observação: Quartos coletivos que podem comportar uma a quatro pessoas (depende da procura/disponibilidade), chuveiro elétrico, segurança 24 h, todos com camas box, ar-condicionado e wi-fi.

Contato: email: [cetrec\@epagri.sc.gov.br](mailto:cetrec@epagri.sc.gov.br){.email}
