---
title: "Edições anteriores"
description: |
---

## 2004

**Local**

Universidade Federal de Viçosa\
Viçosa, MG

**Comissão Organizadora**

Francisco X. R. do Vale (UFV) (Coordenador)\
Armando Bergamim Filho (ESALQ/USP)\
Eduardo S. G. Mizubuti (UFV)\
Fabrício de Ávila Rodrigues (UFV)\
Laércio Zambolim (UFV)\
Lilian Amorim (ESALQ/USP)\
Luiz Antonio Maffia (UFV)

**Equipe de Apoio**

Alessandra Bernardes (Mestranda)\
Antônio J. Macabeu (Técnico)\
Carol Morgado (Eng. Agr.)\
Cristian A.de Souza (Graduando)\
Flávia V. Corrêa (Graduanda)\
Gisele Domiciano (Graduanda)\
Janilson G. da Rocha (Mestrando)\
Kelly L. de Araújo (Mestranda)\
Max L. Resende (Mestrando)


## 2007

**Local**
Campos do Jordão


## 2010

**Local**
Bento Gonçalves

## 2013

**Website do evento**

[http://www.lemid.ufpr.br/wpde.html](http://www.lemid.ufpr.br/wpde.html)


**Local e data** 
 
Pestana Curitiba Convention Center, Curitiba-PR    
2 a 4 de ezembro de 2013

**Comissão Organizadora**

Presidente:  
Louise Larissa May De Mio (UFPR)

Vice-presidente:  
Lilian Amorim (ESALQ)  

**Comissão Científica **   
Armando Bergamin Filho (ESALQ/USP)    
Cristiano Nunes Nesi (EPAGRI)   
Maristella Dalla Pria (UEPG)  
Nilceu Ricetti Xavier de Nazareno (IAPAR)    
Paulo Ribeiro Justiniano Junior (UFPR)  

**Outros membros**
Programa cultural:  
Giselda Alves (UFPR)    

Publicaçao:  
Rafaele Regina Moreira(UFPR)   

Logística:  
Ana Claudia Klosowski (UFPR)      

Tesoureiro:  
Fabrício Packer Gonçalves (IAPAR)   

Secretaria:  
Caroline Grisbach (UFPR) 

## 2016

**Website do evento**

[https://www.embrapa.br/epidemio-brasil/introducao](https://www.embrapa.br/epidemio-brasil/introducao)



**Local e data**
 
Auditório 1 da Embrapa Mandioca e Fruticultura, Cruz das Almas (BA)  
7 a 9 de dezembro de 2016.

**Comissão Organizadora**

Presidente:    
Francisco Ferraz Laranjeira (Embrapa Mandioca e Fruticultura)  

Membro:  
Marcela Silva Nascimento (Embrapa Mandioca e Fruticultura)  

**Comitê Técnico-Científico**

Armando Bergamin Filho (ESALQ/USP)       
Emerson M. Del Ponte (UFV)      
Karina Gramacho (CEPLAC)  
Renato Bassanezi (Fundecitrus)  
Sami Jorge Michereff (UFRPE)    
Suely Xavier Brito Silva (Adab)    

**Outros membros**

Carlos Bragança (UFRB)  
Fernando Haddad (Embrapa Mandioca e Fruticultura)  
Leandro Souza Rocha (Embrapa Mandioca e Fruticultura)  
Paulo Ernesto Meissner (Embrapa Mandioca e Fruticultura)  
Quelmo Novaes (UESB)  
Saulo Alves Santos de Oliveira (Embrapa Mandioca e Fruticultura)  Thiago Alves Santos de Oliveira (UFRB)    

**Comissão de Divulgação**

Léa Ângela Assis Cunha (Embrapa Mandioca e Fruticultura)    
Anapaula Rosário Lopes (Embrapa Mandioca e Fruticultura)    
Daniela Aguiar Santos Tavares (Embrapa Mandioca e Fruticultura)    





